server:
  port: 8080
  servlet:
    context-path: /dsDemo
spring:
  datasource:
    sql-trace: true
    sql-show: true
    sql-trace-max-size: 100
    sql-exec-slow-time: 1
    sql-trace-timeout: 60000
    sql-trace-timeout-scan-period: 6000
    sql-exec-alert-action: cn.beecp.starter.demo.TestAlert
    ds-ids: ds1,ds2
    combineId: combineDs
    combinePrimaryId: ds1
    ds1:
      primary: true
      username: root
      password: ''
      jdbcUrl: jdbc:mysql://localhost:3306/test
      type: cn.beecp.BeeDataSource
      driverClassName: com.mysql.jdbc.Driver
      connectProperties: socketTimeout=6000&connectTimeout=6000


    ds2:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/test
      password: ''
      username: root
      type: cn.beecp.BeeDataSource
